### ISSUE TITLE
[BUG] Budget Amount Spent

### ISSUE THREAD

**Issue by julienkessels** [agstrike/silverstrike#104]
When I go into budgets, and I check for a specific category, it only shows the amount of one item of that category and not the summed up amount of each items for that category.

<img width="789" alt="Screenshot 2019-08-04 at 22 27 29" src="https://user-images.githubusercontent.com/9723073/62428870-14047000-b707-11e9-84fe-a83d47aeb4b2.png">
<img width="717" alt="Screenshot 2019-08-04 at 22 26 52" src="https://user-images.githubusercontent.com/9723073/62428871-149d0680-b707-11e9-828d-9fabda93a6a1.png">

**Comment by Shaent** [comment]
Am I correct that the fix for this bug is **not** merged into release version 0.1.3? Because I am still getting this bug with my docker setup following the instructions provided here: https://silverstrike.org/docker/ using the latest tag.

Also I am confused why silverstrike is version 0.1.3 and not 0.1.4 using the docker setup linked above.

I would really appreciate if somebody could clarify this for me! Thank you!

**Comment by simhnna** [comment]
yeah. I didn't do a real release for quite some time. I've merged a new dockerfile into the main repository and would like to test it out a little and would then create a new tagged release

**Comment by Shaent** [comment]
Thank you for the info. I also already tried the docker setup using the dev tagged image. Unfortunately I always get an http 400 error using the dev image. If you need any help testing your new docker file, I could maybe take a look.

**Comment by simhnna** [comment]
I've pushed some docker-compose configs here https://github.com/agstrike/docker/tree/update-docs

It's still all pointing to the dev image and I haven't run any of the production examples myself yet. I just set up the demo stack today for myself. If you want to play around with them feel free, just be sure to create backups if you try this on your real data

**Comment by Shaent** [comment]
Hi, I have played around with the above linked docker-compose file and also built an image manually from the master branch. Unfortunately I cannot connect to silverstrike in both cases. Using the above linked docker-compose files does not work when using the dev image (Getting the http 400 error). Using the latest image works without any issue.

Building my own image from the master branch also results, as mentioned above, in an http 400 error. Do you maybe have any idea why this is happening? Any hints or tips regarding the issue?

Also feel free to move/close this issue if my problems do not belong here :)!
