### ISSUE TITLE
Budgetapp vs Silverstrike

### ISSUE THREAD

**Issue by jtagcat** [agstrike/silverstrike#108]
These 2 look very similar, how do they compare?

**Comment by jtagcat** [comment]
https://github.com/paukiatwee/budgetapp/issues/22

**Comment by simhnna** [comment]
I don't see a list of features anywhere there and it looks like I need to actually sign up to access the demo, so I'm not able to actually see it running. They said, that silverstrike offered more features. I guess you'll have to play around with the demos yourself...
