### ISSUE TITLE
Docker: could not translate host name "database"

### ISSUE THREAD

**Issue by leisefuxX** [agstrike/silverstrike#132]
hi there,

i wanted to give AgS a try and took the .yaml from the website to deploy to my docker but it refuses to start with error

> " django.db.utils.OperationalError: could not translate host name "database" to address: Temporary failure in name resolution"

i then added 
`  database:
    container_name: database
    hostname: database` 
to the db-part and 
`  app:
    container_name: silverstrike
    hostname: silverstrike`
to the app part. still no luck.

what am i missing? running clean unmodified docker on stock ubuntu 20.04.3

**Comment by simhnna** [comment]
are you sure you copied the file as is? Can you double check and if it still doesn't work, please paste your file contents in the issue

**Comment by leisefuxX** [comment]
there was a typo in my yaml. Sorry for the inconvenience. my bad

**Comment by simhnna** [comment]
no problem
