### ISSUE TITLE
Docker Image for App?

### ISSUE THREAD

**Issue by benyanke** [agstrike/silverstrike#53]
Have you considered building a docker image for it?

I am looking at doing so for my own server (everything running on my server is docker), but don't want to duplicate efforts.

If you do it yourself, here's a nice starting point I found:
https://www.caktusgroup.com/blog/2017/03/14/production-ready-dockerfile-your-python-django-app/

**Comment by simhnna** [comment]
Yeah, I knew I'd have to create an image sometime...

I just created a repo where the docker files live over at [here]](https://github.com/agstrike/docker)

I'll be providing two images:
* **latest** will always be the last actual release of SilverStrike
* **dev** will be the last commit of the master branch

I still need to add documentation on how to use them, but if you want to give them a try you are welcome.
You will need to setup a useraccount on the command line before you can do anything, you'll have to execute the same command mentioned in the setup guide in the docker container.

I'll leave the issue open until I add proper docs, if you find anything that could be improved, don't hesitate to state that :-)

**Comment by benyanke** [comment]
Looks great - if I decide to use this personally, I'll see what I can do to clean it up so you don't need to run container commands manually.

**Comment by simhnna** [comment]
Well I currently only support one user per instance, once more are supported the issue will go away.

**Comment by simhnna** [comment]
Here's some docs
https://silverstrike.tk/docker/

I haven't done any real usage of it, so please tell me if you encounter any issues

**Comment by benyanke** [comment]
You bet - I think I plan to use this, so I'll give it a try and let you know or PR if I have issues or fixes.

**Comment by simhnna** [comment]
@LukasWerfel not sure what exactly you would want the docker image to do? You can currently get a dev env by just running a couple of commands:
```
python -m venv demo/env
source demo/env/bin/activate
python setup.py develop
python ./demo/manage.py migrate
python ./demo/manage.py createsuperuser
python ./demo/manage.py runserver
```
