### ISSUE TITLE
Request: Documentation: Difference vs Firefly III

### ISSUE THREAD

**Issue by Vandivier** [agstrike/silverstrike#61]
At a high level, I see the back end here is Python and [Firefly](https://github.com/firefly-iii/firefly-iii)'s back end is PHP. What are the other current and planned differences?

**Comment by simhnna** [comment]
Does [this](https://silverstrike.tk/overview/) answer your questions? 

If you have anything else you want to know just ask

**Comment by Vandivier** [comment]
Perfect!

**Comment by ktaragorn** [comment]
Not enough.. Firefly has auto rules.. Silverstrike doesnt seem to have.. or am i mistaken?

**Comment by simhnna** [comment]
No it doesn't have them yet. I was thinking about implementing something like that the other day, but didn't really need it. If you'd like to have such a feature open an issue describing the usecase and how it should work. I can think about it then. My priority is to get the features in that I want/need. If something sounds interesting/fun I try to add it.
I'm currently a little short on time and mainly working on a new api for silverstrike together with a reactive frontend, so some features can be implemented directly in the client. Will take some time, but some of the issues I have will be easier to implement once I finish the work on that...

**Comment by ktaragorn** [comment]
It would be good to update the above linked article to add this point. I will create an issue
