### ISSUE TITLE
Better representation of number

### ISSUE THREAD

**Issue by hoangddt** [agstrike/silverstrike#66]
Current display of number is really hard to read.

For example this screenshot below.

![screen shot 2018-07-20 at 6 37 44 pm](https://user-images.githubusercontent.com/9208429/43000545-1099c078-8c4c-11e8-8d14-f68a7c057fe7.png)

Please format the output number in a better way (add comma, or word,...) some thing like this: https://docs.djangoproject.com/en/2.0/ref/contrib/humanize/

**Comment by simhnna** [comment]
I just didn't try it with such numbers.. :grin: 
I guess using the intcomma filter is ok.

**Comment by simhnna** [comment]
fixed in 94cffcb
