### ISSUE TITLE
Add weekly and biweekly options to recurring transactions

### ISSUE THREAD

**Issue by roanutil** [agstrike/silverstrike#67]
Weekly and biweekly are both pretty basic options for recurring transaction intervals. There are likely more recurrence options needed but these two are simple to add and fundamental.

**Comment by simhnna** [comment]
While I don't need them myself I have nothing against adding support for them. Although I guess that a more general recurrence system would be better. Cause the next will come and ask for 1. day of month, the next for the last workday,....

Do you have ideas on how to model this in a nice way?

**Comment by roanutil** [comment]
I agree that there is room for making the recurring intervals more flexible. For now, I think most common cases are covered with these added. That's why I went ahead and added this issue and pull request. It's "drop in" so it costs nothing. 

Right now, I'm working on issue #62. But once I make progress on that, I'll think more on how to better model this.

**Comment by roanutil** [comment]
Something to note on how I added these options to the model. It will cause issues with any existing data in the database. As I added the new values in ascending order. So any previously created monthly transactions will now show as weekly. Considering it's still pre-release this may not be a big issue.

I didn't want to add them out of order. But it will cause issues as currently implemented.

**Comment by simhnna** [comment]
yeah, that won't work... I'm using it in production :-)

let's see if we get somewhere in #62 and then tackle this one :-)

**Comment by roanutil** [comment]
Issue will be addressed by current rework-recurrences branch. Closing
