### ISSUE TITLE
Errors in Wiki page of Development Setup 

### ISSUE THREAD

**Issue by mohitkh7** [agstrike/silverstrike#79]
The [development setup wiki page](https://github.com/agstrike/silverstrike/wiki/Development-Setup) has following errors.
1. Packages through pip are being installed globally as virtual environment is not activated before installation.
```
python3 -m venv env
pip install Django django-widget-tweaks python-dateutil django-allauth
```
2. Running `python manage xxx` commands give following error

```
~silverstrike/demo$ python manage migrate
python: can't open file 'manage': [Errno 2] No such file or directory
```
All such commands should be `python manage.py xxx`

3. Version of packages are not mentioned in following command. We can create `requirments.txt` file and install packages with exact version using it.

**Comment by simhnna** [comment]
I removed the wiki and moved the dev setup page under the setup menu
