### ISSUE TITLE
Import from Emails Automatically with Interactive Slack Messages

### ISSUE THREAD

**Issue by speedyflipper** [agstrike/silverstrike#85]
I currently have a script I use to download emails from Chase and other banks to automatically add transactions to my database, which coincidentally was setup very similar to this program, and send slack messages which can modify the transactions.

Since finding this I've been running both concurrently with queries to copy the data between the databases. I have started working to incorporate the emails and slack into silverstrike but am fairly new to django.

My first question is should I create this as a separate django app within the project or use the existing app? Nothing I'm adding will affect the front-end with the exception of two fields in the account model (email address and bank). The rest of the scripts will need to run the background. Currently I use schedule and multiprocessing to accomplish this but don't think that would be within the best practices of django.

I also needed to create a new endpoint to get the requests from the slack messages. I did this by adding a new view that can capture the post request

Any pointers or suggestions would be greatly appreciated.

**Comment by simhnna** [comment]
So you want to achieve the following:

1. You want to have a command that you can run periodically that fetches emails, extracts transactions from there and adds them to the database
2. On adding these transactions you want to post messages to a slack channel
3. You want to be able to interact with the messages on slack, updating the database

If I got this right, you can probably create a seperate app that have a management command that can do your import stuff.
You can then add a view that accepts slack post requests. As for the account changes you can add a model in your app with a 1-1 relationship to account and either overwrite the template or whole views with whatever changes you need.

* [overwriting views](https://blog.yourlabs.org/post/19777151073/how-to-override-a-view-from-an-external-django-app)
* [extending model](https://docs.djangoproject.com/en/2.1/topics/db/examples/one_to_one/)
* [management commands](https://docs.djangoproject.com/en/2.1/howto/custom-management-commands/)

I haven't done overwriting myself yet in django, but I'm willing to incorporate any changes needed to make it as easy as possible for you and others to extend silverstrike. You might need to use some signals that I would have to add to silverstrike, just tell me about that if you need it.

If you think your code might be interesting for others and are willing to share, I guess you can publish your app in the agstrike namespace
