### ISSUE TITLE
"Withdrawl" vs "Withdrawal"

### ISSUE THREAD

**Issue by wilt00** [agstrike/silverstrike#88]
Not to be a massive pedant, but if we're going to be pedantic anywhere, financial software is a great place for it. :D

The correct spelling of the word is "withdrawal", with an "a", not "withdrawl". At the very least, the UI should use this spelling, even if internal variables don't change.

**Comment by simhnna** [comment]
I'm aware and I wanted to change it in the past. 

What's your opinion on credit/debit vs. deposit/withdrawal?

**Comment by wilt00** [comment]
Personally, I feel as though "deposit/withdrawal" is more approachable and less confusing than "credit/debit", since it seems more common to hear "credit" and "debit" in the context of e.g. "credit card" rather than transactions. I've just checked my bank's website, and they use "deposit/withdrawal" as well.
