### ISSUE TITLE
Request: Additional reccurence frequencies

### ISSUE THREAD

**Issue by scottydelicious** [agstrike/silverstrike#96]
I would like to request a feature for recurrent transactions. Currently the model supports Monthly, Quarterly, Biannually and Annually.

I would like the ability to schedule recurrent transactions as weekly with the granularity of choosing, for example, every Friday, or every other (every 2) Wednesdays.

**Comment by simhnna** [comment]
That is possible in the rework-recurrences branch. I've not had that much time to work on silverstrike in the past few months because I started a new job... I'll try to get some time to get it merged

**Comment by simhnna** [comment]
It's in master now
